export const justMockedSettlementData = [
    {
      summary: [
        { label: "Non-settled transactions", value: "1" },
        { label: "Fee percent", value: "3%" },
        { label: "Fixed Fee", value: "0.80 EUR" },
        { label: "Settlement Fee", value: "1.50%" },
        { label: "Settlement Cost", value: "749.69 EUR" },
      ],
      totalAmounts: [
        { label: "Total Amount Before Fees", value: "51525.01 EUR" },
        { label: "Total Amount After Fees", value: "49979.25 EUR" },
      ],
      totalPayout: "49229.56 EUR",
      transactions: [
        {
          id: 9,
          txId: "bd73d2d8cab5fc8d6aa2c0ca",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "11833.53",
          status: "PAYMENT_CREATED",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2025-04-27T07:42:15.487Z",
          updatedAt: "2025-06-23T14:00:34.896Z",
          sandbox: true,
          isSettled: true,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 2,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
        {
          id: 10,
          txId: "6ead70d162bd73de87fed4d0",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "27035.12",
          status: "PAYMENT_PROCESSING",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2024-06-07T16:47:40.373Z",
          updatedAt: "2025-03-15T19:18:19.840Z",
          sandbox: true,
          isSettled: false,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 1,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
      ],
    },
    {
      summary: [
        { label: "Non-settled transactions", value: "1" },
        { label: "Fee percent", value: "3%" },
        { label: "Fixed Fee", value: "0.80 EUR" },
        { label: "Settlement Fee", value: "1.50%" },
        { label: "Settlement Cost", value: "749.69 EUR" },
      ],
      totalAmounts: [
        { label: "Total Amount Before Fees", value: "51525.01 EUR" },
        { label: "Total Amount After Fees", value: "49979.25 EUR" },
      ],
      totalPayout: "49229.56 EUR",
      transactions: [
        {
          id: 7,
          txId: "bd73d2d8cab5fc8d6aa2c0ca",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "11833.53",
          status: "PAYMENT_CREATED",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2025-04-27T07:42:15.487Z",
          updatedAt: "2025-06-23T14:00:34.896Z",
          sandbox: true,
          isSettled: true,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 2,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
        {
          id: 8,
          txId: "6ead70d162bd73de87fed4d0",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "27035.12",
          status: "PAYMENT_PROCESSING",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2024-06-07T16:47:40.373Z",
          updatedAt: "2025-03-15T19:18:19.840Z",
          sandbox: true,
          isSettled: false,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 1,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
      ],
    },
    {
      summary: [
        { label: "Non-settled transactions", value: "1" },
        { label: "Fee percent", value: "3%" },
        { label: "Fixed Fee", value: "0.80 EUR" },
        { label: "Settlement Fee", value: "1.50%" },
        { label: "Settlement Cost", value: "749.69 EUR" },
      ],
      totalAmounts: [
        { label: "Total Amount Before Fees", value: "51525.01 EUR" },
        { label: "Total Amount After Fees", value: "49979.25 EUR" },
      ],
      totalPayout: "49229.56 EUR",
    },
    {
      summary: [
        { label: "Non-settled transactions", value: "1" },
        { label: "Fee percent", value: "3%" },
        { label: "Fixed Fee", value: "0.80 EUR" },
        { label: "Settlement Fee", value: "1.50%" },
        { label: "Settlement Cost", value: "749.69 EUR" },
      ],
      totalAmounts: [
        { label: "Total Amount Before Fees", value: "51525.01 EUR" },
        { label: "Total Amount After Fees", value: "49979.25 EUR" },
      ],
      totalPayout: "49229.56 EUR",
      transactions: [
        {
          id: 5,
          txId: "bd73d2d8cab5fc8d6aa2c0ca",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "11833.53",
          status: "PAYMENT_CREATED",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2025-04-27T07:42:15.487Z",
          updatedAt: "2025-06-23T14:00:34.896Z",
          sandbox: true,
          isSettled: true,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 2,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
        {
          id: 6,
          txId: "6ead70d162bd73de87fed4d0",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "27035.12",
          status: "PAYMENT_PROCESSING",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2024-06-07T16:47:40.373Z",
          updatedAt: "2025-03-15T19:18:19.840Z",
          sandbox: true,
          isSettled: false,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 1,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
      ],
    },
    {
      summary: [
        { label: "Non-settled transactions", value: "1" },
        { label: "Fee percent", value: "3%" },
        { label: "Fixed Fee", value: "0.80 EUR" },
        { label: "Settlement Fee", value: "1.50%" },
        { label: "Settlement Cost", value: "749.69 EUR" },
      ],
      totalAmounts: [
        { label: "Total Amount Before Fees", value: "51525.01 EUR" },
        { label: "Total Amount After Fees", value: "49979.25 EUR" },
      ],
      totalPayout: "49229.56 EUR",
      transactions: [
        {
          id: 1,
          txId: "bd73d2d8cab5fc8d6aa2c0ca",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "11833.53",
          status: "PAYMENT_CREATED",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2025-04-27T07:42:15.487Z",
          updatedAt: "2025-06-23T14:00:34.896Z",
          sandbox: true,
          isSettled: true,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 2,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
        {
          id: 2,
          txId: "6ead70d162bd73de87fed4d0",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "27035.12",
          status: "PAYMENT_PROCESSING",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2024-06-07T16:47:40.373Z",
          updatedAt: "2025-03-15T19:18:19.840Z",
          sandbox: true,
          isSettled: false,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 1,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
      ],
    },
    {
      summary: [
        { label: "Non-settled transactions", value: "1" },
        { label: "Fee percent", value: "3%" },
        { label: "Fixed Fee", value: "0.80 EUR" },
        { label: "Settlement Fee", value: "1.50%" },
        { label: "Settlement Cost", value: "749.69 EUR" },
      ],
      totalAmounts: [
        { label: "Total Amount Before Fees", value: "51525.01 EUR" },
        { label: "Total Amount After Fees", value: "49979.25 EUR" },
      ],
      totalPayout: "49229.56 EUR",
      transactions: [
        {
          id: 3,
          txId: "bd73d2d8cab5fc8d6aa2c0ca",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "11833.53",
          status: "PAYMENT_CREATED",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2025-04-27T07:42:15.487Z",
          updatedAt: "2025-06-23T14:00:34.896Z",
          sandbox: true,
          isSettled: true,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 2,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
        {
          id: 4,
          txId: "6ead70d162bd73de87fed4d0",
          txReferenceId: "",
          providerId: 1,
          additionalInfo: null,
          amount: "27035.12",
          status: "PAYMENT_PROCESSING",
          initialRequest: {
            email: "alexanmiro@gmail.com",
            firstName: "alex",
            lastName: "anmiro",
            merchantId: "civis",
          },
          returnUrl: "null",
          webhookUrl: "null",
          rawStatus: "",
          createdAt: "2024-06-07T16:47:40.373Z",
          updatedAt: "2025-03-15T19:18:19.840Z",
          sandbox: true,
          isSettled: false,
          settlementDate: null,
          settlementAmount: "0.00",
          statusChecks: 1,
          merchant: {
            name: "Kunde Inc",
            host: "gigantic-median.com",
            label: "despecto",
          },
          provider: {
            name: "Bartell, Cole and Effertz",
            apiSlug: "volva-delibero-cogito-caute",
          },
          webhooks: [],
        },
      ],
    },
  ];